version: 11.0.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova_Epinova.Infrastructure
  sonarcloudkey:
    secure: a8EBBaKMSil4vIqG9OeOqIrroedM5kAXxVMOpdqIAoAdFr2WUz4DZEm0QVQacmAS
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
- cmd: choco install "sonarscanner-msbuild-net46" -y
- cmd: SonarScanner.MSBuild.exe begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.login=%sonarcloudkey%"
after_build:
- cmd: SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
test:
  categories:
    except:
    - Integration
    - Manual
cache:
  - packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: /L7BuZN2mNqeHYM5tnD8Lyh5j+k/nd3vuurOt4zYwmCGTKcGvEo3afO0MWOTj5Yn
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_BRANCH: master