version: 11.1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova.Infrastructure
  sonarcloudkey:
    secure: 0VvcxYCPLglmyB87e5B1vRk0nHq8KUX0ND/qLkCs1RaGULzo1Q+XPHOZgioTbEPZ
  testFilter: Category!=Integration&Category!=Manual
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
- cmd: IF DEFINED sonarcloudkey choco install opencover.portable -y
- cmd: IF DEFINED sonarcloudkey dotnet tool install --global dotnet-sonarscanner
- cmd: IF DEFINED sonarcloudkey dotnet sonarscanner begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.branch.name=%APPVEYOR_REPO_BRANCH%" /d:"sonar.login=%sonarcloudkey%" /d:sonar.cs.opencover.reportsPaths="%APPVEYOR_BUILD_FOLDER%\opencover.results.xml" /d:sonar.cs.vstest.reportsPaths="%APPVEYOR_BUILD_FOLDER%\test.results*.xml"
after_test:
- cmd: IF DEFINED sonarcloudkey dotnet sonarscanner end /d:"sonar.login=%sonarcloudkey%"
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- cmd: IF DEFINED sonarcloudkey (OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test --no-build -c %configuration% -l \"trx;LogFileName=%APPVEYOR_BUILD_FOLDER%\test.results.xml\" --filter %testFilter%" -output:%APPVEYOR_BUILD_FOLDER%\opencover.results.xml -coverbytest:*Tests.dll -oldStyle) ELSE (dotnet test --no-build -c %configuration% --filter %testFilter%)
#cache:
#  - packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: M+b7dlgbK5GWibG7RSV5AtkA4EkVGF6+RC49j5bVeJwTbKxKgSkeEiE60J4uYEVf
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_BRANCH: master