version: 11.1.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
#platform: Any CPU
environment:
  sonarcloudorg: epinova
  sonarcloudproj: Epinova.Infrastructure
  sonarcloudkey:
    secure: 0VvcxYCPLglmyB87e5B1vRk0nHq8KUX0ND/qLkCs1RaGULzo1Q+XPHOZgioTbEPZ
  targetFramework: netstandard2.0
init:
- cmd: nuget sources add -Name Episerver -Source http://nuget.episerver.com/feed/packages.svc/
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
- cmd: IF DEFINED sonarcloudkey choco install sonarscanner-msbuild-net46 opencover.portable -y && SonarScanner.MSBuild.exe begin /k:"%sonarcloudproj%" /d:"sonar.host.url=https://sonarcloud.io" /o:"%sonarcloudorg%" /d:"sonar.branch.name=%APPVEYOR_REPO_BRANCH%" /d:"sonar.login=%sonarcloudkey%" /d:sonar.cs.opencover.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.opencover.results.xml" /d:sonar.cs.xunit.reportsPaths="%APPVEYOR_BUILD_FOLDER%\xunit.test.results.xml"
after_test:
- cmd: IF DEFINED sonarcloudkey SonarScanner.MSBuild.exe end /d:"sonar.login=%sonarcloudkey%"
pull_requests:
  do_not_increment_build_number: true
build:
  publish_nuget: true
  verbosity: minimal
test_script:
- cmd: 'OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.exe" -targetargs:"tests\bin\%configuration%\%targetFramework%\Epinova.InfrastructureTests.dll -noshadow -xml xunit.test.results.xml -appveyor -notrait Category=Integration -notrait Category=Manual" -output:%APPVEYOR_BUILD_FOLDER%\xunit.opencover.results.xml -coverbytest:*Tests.dll'
cache:
  - packages -> **\packages.config
deploy:
  provider: NuGet
  api_key:
    secure: M+b7dlgbK5GWibG7RSV5AtkA4EkVGF6+RC49j5bVeJwTbKxKgSkeEiE60J4uYEVf
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_BRANCH: master